#For more information about setup-java see: https://github.com/actions/setup-java#supported-distributions
#For more information about codecov see: https://github.com/codecov/codecov-action
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
          with:
            distribution: '<distribution>'
            java-version: ${{ matrix.java }}
            cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)